name: income
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none' 

# Version information
version: 1.0.0+1

# Environment settings
environment:
  sdk: ">=3.5.0 <4.0.0"

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Flutter-specific settings
flutter:
  uses-material-design: true

  # Assets configuration
  assets:
    - assets/

  # Uncomment and configure fonts if needed
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
